### PR TITLE
make all modals again without using daisy UI

### PR DESCRIPTION
**Pull request by smartdev322**

### CODE REVIEW

**Comment by lcb931023** [comment]
Thanks for the PR.

For **adjust how event log timestamp works**:

image
1. Please add a toggle to switch between "Day X" display and regular display of time.

image

2. When in "Day X" display mode, please also log the day X for actions in the project log, instead of the exact date.

**Comment by lcb931023** [comment]
For **Make it obvious when someone's in GM mode**:

image
There's currently a runtime error when you toggle open the GM mode.

The GM panel is not showing, and neither are the GM alert.

**Comment by smartdev322** [comment]
a runtime error has occurred because I changed the structure of "gmUsers".
Please try with a new game id or delete the gmUsers in your DB in firebase.

**Comment by lcb931023** [comment]
I see. We need to be verbal about these backend-breaking changes. The game is about to be launched, and it would be a problem if our updates break an ongoing game session.

**Comment by lcb931023** [comment]
Ideally, we would not be making breaking changes to the firebase backend. In situations where that is inevitable, let's create data migration scripts that reform an existing session into the new storage format.

**Comment by smartdev322** [comment]
How to create data migration scripts then?

**Comment by lcb931023** [comment]
It looks like the GM issue only impacts the #dev session. I've fixed it manually in firebase.

**Pull request merged**
